altside = int(input("Enter the length of the alternate side: "))
baseside = int(input("Enter the length of the base side: "))
c=((altside**2)+(baseside**2))
hyp=c**(1/2)
print("Hypotenuse of the Triangle: ", hyp)